// generated by cdktf get
// git::https://github.axa.com/datalab-italy/dl-utilities//resource-naming?ref=master
import { TerraformModule } from 'cdktf';
import { Construct } from 'constructs';
export interface ResourceNamingOptions {
  /**
   * Datalab prefix
   */
  readonly datalabPrefix?: string;
  /**
   * Datalab project name
   */
  readonly datalabProject?: string;
  /**
   * Environment [nonprod|preprod|prod]
   */
  readonly env?: string;
  /**
   * AWS Region (ex. eu-central-1)
   */
  readonly region?: string;
  /**
   * Name to add to resource name (calculated)
   */
  readonly resourceName: string;
  /**
   * AWS Resource type that the name will be generated by this module.
   */
  readonly resourceType: string;
}
export class ResourceNaming extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, options: ResourceNamingOptions) {
    super(scope, id, {
      source: 'git::https://github.axa.com/datalab-italy/dl-utilities//resource-naming?ref=master',
    });
    this.datalabPrefix = options.datalabPrefix;
    this.datalabProject = options.datalabProject;
    this.env = options.env;
    this.region = options.region;
    this.resourceName = options.resourceName;
    this.resourceType = options.resourceType;
  }
  public get datalabPrefix(): string | undefined {
    return this.inputs['datalab_prefix'] as string | undefined;
  }
  public set datalabPrefix(value: string | undefined) {
    this.inputs['datalab_prefix'] = value;
  }
  public get datalabProject(): string | undefined {
    return this.inputs['datalab_project'] as string | undefined;
  }
  public set datalabProject(value: string | undefined) {
    this.inputs['datalab_project'] = value;
  }
  public get env(): string | undefined {
    return this.inputs['env'] as string | undefined;
  }
  public set env(value: string | undefined) {
    this.inputs['env'] = value;
  }
  public get region(): string | undefined {
    return this.inputs['region'] as string | undefined;
  }
  public set region(value: string | undefined) {
    this.inputs['region'] = value;
  }
  public get resourceName(): string {
    return this.inputs['resource_name'] as string;
  }
  public set resourceName(value: string) {
    this.inputs['resource_name'] = value;
  }
  public get resourceType(): string {
    return this.inputs['resource_type'] as string;
  }
  public set resourceType(value: string) {
    this.inputs['resource_type'] = value;
  }
  public get composedPrefixOutput() {
    return this.getString('composed_prefix')
  }
  public get composedProjectPrefixOutput() {
    return this.getString('composed_project_prefix')
  }
  public get composedResourceNameOutput() {
    return this.getString('composed_resource_name')
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
